name: Release Go project

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: GoReleaser build
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: wangyoucao577/go-release-action@v1.25
        with:
          github_token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.17
          binary_name: gocrypt
          ldflags: "-X github.com/minghsu0107/gocrypt/cmd.Version=${{ github.ref_name }} -s -w"